import type { ContrastPair, Pronoun } from './types'

// ============================================================
// INDEFINIDO / IMPERFECTO CONTRAST PAIRS
// 30+ pairs using high-frequency social verbs
// ============================================================

export const CONTRAST_PAIRS: ContrastPair[] = [
  {
    id: 'quedar_1',
    pronoun: 'yo',
    verb: 'quedar',
    indefinidoSentence: 'Ayer ______ con Pablo para tomar algo.',
    indefinidoExpected: 'quedé',
    indefinidoContext: 'Ayer = a specific, completed meeting. One flash, done.',
    imperfectoSentence: 'Antes siempre ______ con mis amigos los viernes.',
    imperfectoExpected: 'quedaba',
    imperfectoContext: 'Antes + siempre = an ongoing, repeated habit. The camera was rolling.',
    comparisonNote: 'quedé = we met up (once, specific) | quedaba = we used to meet up (ongoing habit)',
  },
  {
    id: 'ir_1',
    pronoun: 'yo',
    verb: 'ir',
    indefinidoSentence: 'El sábado pasado ______ al mercado de la Boqueria.',
    indefinidoExpected: 'fui',
    indefinidoContext: 'El sábado pasado = one specific visit, completed.',
    imperfectoSentence: 'Antes ______ al mercado todos los sábados.',
    imperfectoExpected: 'iba',
    imperfectoContext: 'Antes + todos los sábados = a regular past habit with no defined end.',
    comparisonNote: 'fui = I went (that one Saturday) | iba = I used to go (every Saturday)',
  },
  {
    id: 'comer_1',
    pronoun: 'nosotros',
    verb: 'comer',
    indefinidoSentence: 'La semana pasada ______ en ese restaurante tan bueno del Born.',
    indefinidoExpected: 'comimos',
    indefinidoContext: 'La semana pasada = a specific, completed meal.',
    imperfectoSentence: 'Cuando vivíamos cerca, siempre ______ allí después del trabajo.',
    imperfectoExpected: 'comíamos',
    imperfectoContext: 'Cuando vivíamos cerca + siempre = an ongoing habit from that period of life.',
    comparisonNote: 'comimos = we ate there (that occasion) | comíamos = we used to eat there (regularly)',
  },
  {
    id: 'conocer_1',
    pronoun: 'yo',
    verb: 'conocer',
    indefinidoSentence: 'La ______ en la fiesta de Marta — hicimos muy buenas migas.',
    indefinidoExpected: 'conocí',
    indefinidoContext: 'Meeting someone for the first time = a specific, completed moment.',
    imperfectoSentence: 'La ______ de antes — éramos del mismo barrio.',
    imperfectoExpected: 'conocía',
    imperfectoContext: 'Knowing someone from before = an ongoing state (you already knew her).',
    comparisonNote: 'conocí = I met her (first meeting, specific moment) | conocía = I knew her (ongoing familiarity)',
  },
  {
    id: 'querer_1',
    pronoun: 'él/ella',
    verb: 'querer',
    indefinidoSentence: 'Lo intentó pero al final no ______ — lo dejó estar.',
    indefinidoExpected: 'quiso',
    indefinidoContext: 'No quiso = he tried but ultimately decided not to (active refusal at a moment).',
    imperfectoSentence: '______ venir pero tenía demasiado trabajo.',
    imperfectoExpected: 'Quería',
    imperfectoContext: 'Quería = an ongoing desire (he wanted to, all along) — then something blocked it.',
    comparisonNote: 'quiso = he tried/decided (in the moment) | quería = he wanted to (ongoing desire, unfulfilled)',
  },
  {
    id: 'poder_1',
    pronoun: 'yo',
    verb: 'poder',
    indefinidoSentence: 'Al final ______ conseguir entrada — había cancelaciones.',
    indefinidoExpected: 'pude',
    indefinidoContext: 'Pude = I managed to (succeeded in getting in — completed achievement).',
    imperfectoSentence: 'Antes no ______ permitirme ese tipo de restaurante.',
    imperfectoExpected: 'podía',
    imperfectoContext: 'Podía = I was able to / had the means (ongoing general ability or financial situation).',
    comparisonNote: 'pude = I managed to (succeeded in one instance) | podía = I was able to / could (ongoing capability)',
  },
  {
    id: 'tener_1',
    pronoun: 'yo',
    verb: 'tener',
    indefinidoSentence: '______ un día horrible — todo salió mal.',
    indefinidoExpected: 'Tuve',
    indefinidoContext: 'A completed day with a defined result — yesterday, done.',
    imperfectoSentence: 'Antes ______ los lunes libres — qué bien se vivía.',
    imperfectoExpected: 'tenía',
    imperfectoContext: 'Antes = in the past, ongoing — a regular situation that was in place.',
    comparisonNote: 'tuve = I had (that specific bad day) | tenía = I had / used to have (ongoing situation)',
  },
  {
    id: 'estar_1',
    pronoun: 'yo',
    verb: 'estar',
    indefinidoSentence: '______ en Barcelona todo el fin de semana — fue genial.',
    indefinidoExpected: 'Estuve',
    indefinidoContext: 'Todo el fin de semana = a completed, bounded stay. It ended.',
    imperfectoSentence: '______ muy cansado cuando me llamaste.',
    imperfectoExpected: 'Estaba',
    imperfectoContext: 'Estaba cansado = an ongoing state that was in place when something else happened.',
    comparisonNote: 'estuve = I was there (bounded, completed visit) | estaba = I was (ongoing state/condition)',
  },
  {
    id: 'llamar_1',
    pronoun: 'él/ella',
    verb: 'llamar',
    indefinidoSentence: 'Me ______ ayer por la mañana — pillé el teléfono a tiempo.',
    indefinidoExpected: 'llamó',
    indefinidoContext: 'Ayer = a specific completed call.',
    imperfectoSentence: 'Me ______ siempre que pasaba algo — éramos muy unidos.',
    imperfectoExpected: 'llamaba',
    imperfectoContext: 'Siempre + éramos unidos = an ongoing habit in that period of the relationship.',
    comparisonNote: 'llamó = he called (that one time) | llamaba = he used to call (habitual)',
  },
  {
    id: 'salir_1',
    pronoun: 'nosotros',
    verb: 'salir',
    indefinidoSentence: 'El viernes ______ de fiesta y lo pasamos fenomenal.',
    indefinidoExpected: 'salimos',
    indefinidoContext: 'El viernes = a specific night out, completed, done.',
    imperfectoSentence: 'Antes ______ todos los fines de semana sin falta.',
    imperfectoExpected: 'salíamos',
    imperfectoContext: 'Antes + todos los fines de semana = a regular past habit, no defined end.',
    comparisonNote: 'salimos = we went out (that Friday) | salíamos = we used to go out (every weekend)',
  },
  {
    id: 'vivir_1',
    pronoun: 'él/ella',
    verb: 'vivir',
    indefinidoSentence: '______ en Madrid dos años y luego se volvió a Barcelona.',
    indefinidoExpected: 'Vivió',
    indefinidoContext: 'Dos años + luego se volvió = a completed, bounded period with a defined end.',
    imperfectoSentence: 'Cuando lo conocí, ______ en el Eixample.',
    imperfectoExpected: 'vivía',
    imperfectoContext: 'Where he lived = ongoing background situation when another event occurred.',
    comparisonNote: 'vivió = he lived (for two years, then it ended) | vivía = he was living (ongoing background)',
  },
  {
    id: 'trabajar_1',
    pronoun: 'tú',
    verb: 'trabajar',
    indefinidoSentence: '______ allí un verano para ganar algo de dinero, ¿no?',
    indefinidoExpected: 'Trabajaste',
    indefinidoContext: 'Un verano = a completed, bounded period of employment.',
    imperfectoSentence: '¿No ______ en Madrid antes de venir aquí?',
    imperfectoExpected: 'trabajabas',
    imperfectoContext: 'Antes = a previous ongoing work situation, no defined end mentioned.',
    comparisonNote: 'trabajaste = you worked (that one summer) | trabajabas = you used to work (ongoing situation)',
  },
  {
    id: 'hablar_1',
    pronoun: 'yo',
    verb: 'hablar',
    indefinidoSentence: '______ con él ayer y me contó todo.',
    indefinidoExpected: 'Hablé',
    indefinidoContext: 'Ayer = one specific conversation, completed.',
    imperfectoSentence: '______ con él casi todos los días cuando éramos vecinos.',
    imperfectoExpected: 'Hablaba',
    imperfectoContext: 'Casi todos los días + cuando éramos vecinos = an ongoing habit from that period.',
    comparisonNote: 'hablé = I spoke (yesterday, that one conversation) | hablaba = I used to speak (regular habit)',
  },
  {
    id: 'beber_1',
    pronoun: 'nosotros',
    verb: 'beber',
    indefinidoSentence: 'Anoche ______ demasiado — hoy estamos destrozados.',
    indefinidoExpected: 'bebimos',
    indefinidoContext: 'Anoche = last night, a completed event with a result (we\'re wrecked today).',
    imperfectoSentence: 'De jóvenes ______ más — ahora somos más sensatos.',
    imperfectoExpected: 'bebíamos',
    imperfectoContext: 'De jóvenes = in our youth, an ongoing habit from that phase of life.',
    comparisonNote: 'bebimos = we drank (last night, completed) | bebíamos = we used to drink (habit when young)',
  },
  {
    id: 'llegar_1',
    pronoun: 'ellos/ellas',
    verb: 'llegar',
    indefinidoSentence: 'De repente ______ todos a la vez — fue un caos.',
    indefinidoExpected: 'llegaron',
    indefinidoContext: 'De repente = a sudden, completed arrival event.',
    imperfectoSentence: 'Siempre ______ tarde — era su costumbre.',
    imperfectoExpected: 'llegaban',
    imperfectoContext: 'Siempre = an ongoing pattern, a habitual way of behaving.',
    comparisonNote: 'llegaron = they arrived (that specific time) | llegaban = they used to arrive (habitually late)',
  },
  {
    id: 'volver_1',
    pronoun: 'yo',
    verb: 'volver',
    indefinidoSentence: '______ tardísimo — eran casi las cuatro.',
    indefinidoExpected: 'Volví',
    indefinidoContext: 'One specific return, completed. It was late that night.',
    imperfectoSentence: 'Antes siempre ______ a casa a comer — vivía cerca del trabajo.',
    imperfectoExpected: 'volvía',
    imperfectoContext: 'Antes + siempre = a regular habit during a previous phase of life.',
    comparisonNote: 'volví = I came home (that night, completed) | volvía = I used to come home (daily habit)',
  },
  {
    id: 'pedir_1',
    pronoun: 'nosotros',
    verb: 'pedir',
    indefinidoSentence: '______ el menú del día — fue la mejor decisión.',
    indefinidoExpected: 'Pedimos',
    indefinidoContext: 'One specific order, at one specific meal.',
    imperfectoSentence: 'Siempre ______ lo mismo en ese sitio — ya nos conocían.',
    imperfectoExpected: 'pedíamos',
    imperfectoContext: 'Siempre + ya nos conocían = an established pattern at that restaurant.',
    comparisonNote: 'pedimos = we ordered (that meal) | pedíamos = we always used to order (the same thing)',
  },
  {
    id: 'cenar_1',
    pronoun: 'ellos/ellas',
    verb: 'cenar',
    indefinidoSentence: 'El jueves ______ en casa de los padres de Jordi.',
    indefinidoExpected: 'cenaron',
    indefinidoContext: 'El jueves = a specific dinner occasion, completed.',
    imperfectoSentence: 'Antes ______ en familia todos los domingos.',
    imperfectoExpected: 'cenaban',
    imperfectoContext: 'Antes + todos los domingos = a family tradition, ongoing in the past.',
    comparisonNote: 'cenaron = they had dinner (that Thursday) | cenaban = they used to have dinner (every Sunday)',
  },
  {
    id: 'pensar_1',
    pronoun: 'yo',
    verb: 'pensar',
    indefinidoSentence: 'Al final ______ que era mejor no decir nada.',
    indefinidoExpected: 'pensé',
    indefinidoContext: 'A concluded thought — a decision reached at a specific moment.',
    imperfectoSentence: '______ que no venías — llevabas una hora de retraso.',
    imperfectoExpected: 'Pensaba',
    imperfectoContext: 'An ongoing thought or belief that was in progress at that moment.',
    comparisonNote: 'pensé = I concluded/decided (at that moment) | pensaba = I was thinking / believed (ongoing)',
  },
  {
    id: 'dormir_1',
    pronoun: 'yo',
    verb: 'dormir',
    indefinidoSentence: 'Anoche ______ fatal — el vecino de arriba estuvo de fiesta.',
    indefinidoExpected: 'dormí',
    indefinidoContext: 'Anoche = last night, a completed night of sleep (or lack of it).',
    imperfectoSentence: 'De estudiante ______ muy poco — siempre había algo que hacer.',
    imperfectoExpected: 'dormía',
    imperfectoContext: 'De estudiante = an ongoing situation during student years, habitual.',
    comparisonNote: 'dormí = I slept (last night) | dormía = I used to sleep (or not sleep — habit)',
  },
  {
    id: 'esperar_1',
    pronoun: 'yo',
    verb: 'esperar',
    indefinidoSentence: '______ cuarenta minutos en la cola — fue una pesadilla.',
    indefinidoExpected: 'Esperé',
    indefinidoContext: 'Cuarenta minutos = a completed, counted wait. Done.',
    imperfectoSentence: '______ en la parada cuando empezó a llover.',
    imperfectoExpected: 'Esperaba',
    imperfectoContext: 'An ongoing action (waiting) that was in progress when something else happened.',
    comparisonNote: 'esperé = I waited (forty minutes, done) | esperaba = I was waiting (ongoing, interrupted)',
  },
  {
    id: 'pasar_1',
    pronoun: 'nosotros',
    verb: 'pasar',
    indefinidoSentence: 'El verano pasado ______ dos semanas en Menorca.',
    indefinidoExpected: 'pasamos',
    indefinidoContext: 'El verano pasado + dos semanas = a completed, bounded period.',
    imperfectoSentence: 'Antes ______ el verano siempre en la misma casa de los abuelos.',
    imperfectoExpected: 'pasábamos',
    imperfectoContext: 'Antes + siempre = an ongoing annual tradition from childhood.',
    comparisonNote: 'pasamos = we spent (last summer, that trip) | pasábamos = we used to spend (every summer, tradition)',
  },
  {
    id: 'comprar_1',
    pronoun: 'él/ella',
    verb: 'comprar',
    indefinidoSentence: '______ el piso en 2019 — tuvo muy buen ojo.',
    indefinidoExpected: 'Compró',
    indefinidoContext: 'En 2019 = a specific, one-off purchase completed in that year.',
    imperfectoSentence: '______ siempre en el mercado del barrio — le encantaba ir.',
    imperfectoExpected: 'Compraba',
    imperfectoContext: 'Siempre = an ongoing shopping habit she had.',
    comparisonNote: 'compró = she bought (the flat, once in 2019) | compraba = she used to buy / would buy (regularly)',
  },
  {
    id: 'buscar_1',
    pronoun: 'ellos/ellas',
    verb: 'buscar',
    indefinidoSentence: '______ piso durante tres meses y al final encontraron uno en Gràcia.',
    indefinidoExpected: 'Buscaron',
    indefinidoContext: 'Durante tres meses + al final encontraron = a completed search with a defined result.',
    imperfectoSentence: '______ algo más tranquilo — estaban hartos del centro.',
    imperfectoExpected: 'Buscaban',
    imperfectoContext: 'An ongoing desire/search that was in progress (context for why they eventually found it).',
    comparisonNote: 'buscaron = they searched (for three months — completed) | buscaban = they were looking for (ongoing desire)',
  },
  {
    id: 'escuchar_1',
    pronoun: 'nosotros',
    verb: 'escuchar',
    indefinidoSentence: 'Anoche ______ ese disco nuevo de Rosalía — está increíble.',
    indefinidoExpected: 'escuchamos',
    indefinidoContext: 'Anoche = one specific listening session, completed.',
    imperfectoSentence: 'De pequeños ______ la radio en el coche con nuestros padres.',
    imperfectoExpected: 'escuchábamos',
    imperfectoContext: 'De pequeños = an ongoing childhood habit.',
    comparisonNote: 'escuchamos = we listened (last night) | escuchábamos = we used to listen (childhood habit)',
  },
  {
    id: 'hacer_1',
    pronoun: 'tú',
    verb: 'hacer',
    indefinidoSentence: '¿Qué ______ el finde? Cuéntame.',
    indefinidoExpected: 'hiciste',
    indefinidoContext: 'El finde = the specific completed weekend.',
    imperfectoSentence: '¿Qué ______ normalmente los domingos cuando eras pequeño?',
    imperfectoExpected: 'hacías',
    imperfectoContext: 'Normalmente + cuando eras pequeño = habitual activity during childhood.',
    comparisonNote: 'hiciste = you did (that specific weekend) | hacías = you used to do (childhood habit)',
  },
  {
    id: 'ver_1',
    pronoun: 'yo',
    verb: 'ver',
    indefinidoSentence: 'Ayer ______ esa serie nueva — me enganchó mogollón.',
    indefinidoExpected: 'vi',
    indefinidoContext: 'Ayer = a specific completed viewing.',
    imperfectoSentence: 'De niño ______ la tele después de comer siempre.',
    imperfectoExpected: 'veía',
    imperfectoContext: 'De niño + siempre = an established childhood routine.',
    comparisonNote: 'vi = I watched (yesterday, done) | veía = I used to watch (daily childhood habit)',
  },
  {
    id: 'leer_1',
    pronoun: 'él/ella',
    verb: 'leer',
    indefinidoSentence: '______ el artículo de un tirón — no pudo parar.',
    indefinidoExpected: 'Leyó',
    indefinidoContext: 'De un tirón = in one sitting, a completed act of reading.',
    imperfectoSentence: '______ muchísimo de joven — era un ratón de biblioteca.',
    imperfectoExpected: 'Leía',
    imperfectoContext: 'De joven + era un ratón de biblioteca = an ongoing characteristic from youth.',
    comparisonNote: 'leyó = he read (that article, done) | leía = he used to read (all the time, habit when young)',
  },
  {
    id: 'coger_1',
    pronoun: 'nosotros',
    verb: 'coger',
    indefinidoSentence: 'El domingo ______ el tren a Valencia — fue un viaje agotador.',
    indefinidoExpected: 'cogimos',
    indefinidoContext: 'El domingo = a specific journey, completed.',
    imperfectoSentence: 'Antes ______ el metro siempre — ahora tengo coche.',
    imperfectoExpected: 'cogíamos',
    imperfectoContext: 'Antes + ahora tengo coche = a past ongoing habit that has since changed.',
    comparisonNote: 'cogimos = we took (the train that Sunday) | cogíamos = we used to take (metro, habitual)',
  },
  {
    id: 'bailar_1',
    pronoun: 'nosotros',
    verb: 'bailar',
    indefinidoSentence: '______ hasta las seis de la mañana — qué noche.',
    indefinidoExpected: 'Bailamos',
    indefinidoContext: 'Until 6am = a completed event with a defined end (the party ended).',
    imperfectoSentence: '______ salsa todos los jueves cuando vivíamos en Madrid.',
    imperfectoExpected: 'Bailábamos',
    imperfectoContext: 'Todos los jueves + cuando vivíamos en Madrid = a regular activity during that period.',
    comparisonNote: 'bailamos = we danced (that night, until 6am) | bailábamos = we used to dance (weekly, in Madrid)',
  },
]

export function getContrastPairsForSession(count: number = 2): ContrastPair[] {
  // Return a random selection of contrast pairs
  const shuffled = [...CONTRAST_PAIRS].sort(() => Math.random() - 0.5)
  return shuffled.slice(0, count)
}
